/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex_201;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.Month;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author ruckenstuhl
 */
public class VelocityGUI extends javax.swing.JFrame {

    VelocityTableModel bl = new VelocityTableModel();
    /**
     * Creates new form VelocityGUI
     */
    public VelocityGUI() {
        initComponents();
        
        table.setModel(bl);
        table.setDefaultRenderer(Object.class, new VelocityTableCellRenderer());
        
        bl.add(new Measurment(LocalDate.of(2013, 10, 8),LocalTime.of(8,31),"GU-RASER1",123,80));
        bl.add(new Measurment(LocalDate.of(2013, 10, 8),LocalTime.of(8,31),"GU-RASER1",123,100));
        bl.add(new Measurment(LocalDate.of(2013, 10, 8),LocalTime.of(8,31),"GU-RASER1",123,110));
        bl.add(new Measurment(LocalDate.of(2013, 10, 8),LocalTime.of(8,31),"GU-RASER1",123,120));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        miHinzufügen = new javax.swing.JMenuItem();
        miLöschen = new javax.swing.JMenuItem();
        miDurchschnitt = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        miHinzufügen.setText("Add");
        miHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHinzufügenActionPerformed(evt);
            }
        });
        popup.add(miHinzufügen);

        miLöschen.setText("Delete");
        popup.add(miLöschen);

        miDurchschnitt.setText("Average");
        miDurchschnitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDurchschnittActionPerformed(evt);
            }
        });
        popup.add(miDurchschnitt);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setComponentPopupMenu(popup);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHinzufügenActionPerformed
        Dialog dialog = new Dialog(this,true);
        dialog.setVisible(true);
        
        if(dialog.isOk()){
            Measurment m = dialog.getM();
            bl.add(m);
        }
    }//GEN-LAST:event_miHinzufügenActionPerformed

    private void miDurchschnittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDurchschnittActionPerformed
        JOptionPane.showMessageDialog(null, bl.average());
    }//GEN-LAST:event_miDurchschnittActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelocityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miDurchschnitt;
    private javax.swing.JMenuItem miHinzufügen;
    private javax.swing.JMenuItem miLöschen;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
